Use Python 3.9, new workers, and Bullseye dependencies
wazo-platform/wazo-ui pull request #141
Opened 2023-02-16 19:50 UTC by sopelj

2023-02-17 14:49 UTC, sopelj commented
Requires: `python3-flask-classful`, `python3-flask-menu`, `python3-flask-session` which are not in Debian and `xivo-certs`

2023-02-17 18:21 UTC, fblackburn1 requested changes

2023-02-17 18:21 UTC, fblackburn1 commented on setup.py
> +    },
From the debian-packaging job, none of these directory are included in the debian package

2023-02-17 20:43 UTC, sopelj commented on setup.py
> +    },
You're right...
It looks like the `package_data` option does not resolve recursively, even with globs. So I had to define a method do it. Otherwise we would have to list all the possible subdirectories and it would get very long and easy to forget to update.

2023-03-01 00:36 UTC, fblackburn1 approved these changes

2023-03-01 00:50 UTC, merged